// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createReview.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$1 from "./loaders/Seals/seals.tsx";
import * as $$$$$$$0 from "./matchers/canonical.ts";
import * as $$$$$$$1 from "./matchers/multipleCanonical.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$3 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Category/BreadcrumbPLP.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$9 from "./sections/Category/SeoText.tsx";
import * as $$$$$$10 from "./sections/Component.tsx";
import * as $$$$$$11 from "./sections/Content/Benefits.tsx";
import * as $$$$$$12 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$13 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$14 from "./sections/Content/Faq.tsx";
import * as $$$$$$15 from "./sections/Content/Features.tsx";
import * as $$$$$$16 from "./sections/Content/Hero.tsx";
import * as $$$$$$17 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$18 from "./sections/Content/Intro.tsx";
import * as $$$$$$19 from "./sections/Content/Line.tsx";
import * as $$$$$$20 from "./sections/Content/Logos.tsx";
import * as $$$$$$21 from "./sections/Content/Partners.tsx";
import * as $$$$$$22 from "./sections/Content/RichText.tsx";
import * as $$$$$$23 from "./sections/Content/Space.tsx";
import * as $$$$$$24 from "./sections/Content/Table.tsx";
import * as $$$$$$25 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$26 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$27 from "./sections/Footer/Footer.tsx";
import * as $$$$$$28 from "./sections/Forms/Contact.tsx";
import * as $$$$$$29 from "./sections/Gallery.tsx";
import * as $$$$$$30 from "./sections/Header/Header.tsx";
import * as $$$$$$31 from "./sections/Iframe.tsx";
import * as $$$$$$32 from "./sections/Images/BannerArray.tsx";
import * as $$$$$$33 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$34 from "./sections/Images/Carousel.tsx";
import * as $$$$$$35 from "./sections/Images/FullBanner.tsx";
import * as $$$$$$36 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$37 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$38 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$39 from "./sections/Institutional/InstitutionalBody.tsx";
import * as $$$$$$40 from "./sections/Layout/Container.tsx";
import * as $$$$$$41 from "./sections/Layout/Flex.tsx";
import * as $$$$$$42 from "./sections/Layout/Grid.tsx";
import * as $$$$$$43 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$44 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$45 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$46 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$47 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$48 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$49 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$50 from "./sections/Product/BuyFloating.tsx";
import * as $$$$$$51 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$52 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$53 from "./sections/Product/NotFound.tsx";
import * as $$$$$$54 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$55 from "./sections/Product/Product.tsx";
import * as $$$$$$56 from "./sections/Product/ProductBuyTogether.tsx";
import * as $$$$$$57 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$58 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$59 from "./sections/Product/ProductReviews.tsx";
import * as $$$$$$60 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$61 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$62 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$63 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$64 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$65 from "./sections/SEO/PageSEO.tsx";
import * as $$$$$$66 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$67 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$69 from "./sections/Theme/defaultColors.ts";
import * as $$$$$$70 from "./sections/Theme/theme.d.ts";
import * as $$$$$$68 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/List/Sections.tsx": $$$0,
    "site/loaders/Seals/seals.tsx": $$$1,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$1,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$2,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$3,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$4,
    "site/sections/Category/BreadcrumbPLP.tsx": $$$$$$5,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$6,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$7,
    "site/sections/Category/CategoryList.tsx": $$$$$$8,
    "site/sections/Category/SeoText.tsx": $$$$$$9,
    "site/sections/Component.tsx": $$$$$$10,
    "site/sections/Content/Benefits.tsx": $$$$$$11,
    "site/sections/Content/BlogPosts.tsx": $$$$$$12,
    "site/sections/Content/CallToAction.tsx": $$$$$$13,
    "site/sections/Content/Faq.tsx": $$$$$$14,
    "site/sections/Content/Features.tsx": $$$$$$15,
    "site/sections/Content/Hero.tsx": $$$$$$16,
    "site/sections/Content/ImageSection.tsx": $$$$$$17,
    "site/sections/Content/Intro.tsx": $$$$$$18,
    "site/sections/Content/Line.tsx": $$$$$$19,
    "site/sections/Content/Logos.tsx": $$$$$$20,
    "site/sections/Content/Partners.tsx": $$$$$$21,
    "site/sections/Content/RichText.tsx": $$$$$$22,
    "site/sections/Content/Space.tsx": $$$$$$23,
    "site/sections/Content/Table.tsx": $$$$$$24,
    "site/sections/Content/Testimonials.tsx": $$$$$$25,
    "site/sections/Content/TextWithImage.tsx": $$$$$$26,
    "site/sections/Footer/Footer.tsx": $$$$$$27,
    "site/sections/Forms/Contact.tsx": $$$$$$28,
    "site/sections/Gallery.tsx": $$$$$$29,
    "site/sections/Header/Header.tsx": $$$$$$30,
    "site/sections/Iframe.tsx": $$$$$$31,
    "site/sections/Images/BannerArray.tsx": $$$$$$32,
    "site/sections/Images/BannerGrid.tsx": $$$$$$33,
    "site/sections/Images/Carousel.tsx": $$$$$$34,
    "site/sections/Images/FullBanner.tsx": $$$$$$35,
    "site/sections/Images/ImageGallery.tsx": $$$$$$36,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$37,
    "site/sections/Institutional/Institutional.tsx": $$$$$$38,
    "site/sections/Institutional/InstitutionalBody.tsx": $$$$$$39,
    "site/sections/Layout/Container.tsx": $$$$$$40,
    "site/sections/Layout/Flex.tsx": $$$$$$41,
    "site/sections/Layout/Grid.tsx": $$$$$$42,
    "site/sections/Layout/GridItem.tsx": $$$$$$43,
    "site/sections/Links/LinkTree.tsx": $$$$$$44,
    "site/sections/Links/Shortcuts.tsx": $$$$$$45,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$46,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$47,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$48,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$49,
    "site/sections/Product/BuyFloating.tsx": $$$$$$50,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$51,
    "site/sections/Product/ImageGallerySlider.tsx": $$$$$$52,
    "site/sections/Product/NotFound.tsx": $$$$$$53,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$54,
    "site/sections/Product/Product.tsx": $$$$$$55,
    "site/sections/Product/ProductBuyTogether.tsx": $$$$$$56,
    "site/sections/Product/ProductDescription.tsx": $$$$$$57,
    "site/sections/Product/ProductInfo.tsx": $$$$$$58,
    "site/sections/Product/ProductReviews.tsx": $$$$$$59,
    "site/sections/Product/ProductShelf.tsx": $$$$$$60,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$61,
    "site/sections/Product/SearchResult.tsx": $$$$$$62,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$63,
    "site/sections/Product/Wishlist.tsx": $$$$$$64,
    "site/sections/SEO/PageSEO.tsx": $$$$$$65,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$66,
    "site/sections/Social/WhatsApp.tsx": $$$$$$67,
    "site/sections/Theme/defaultColors.ts": $$$$$$69,
    "site/sections/Theme/theme.d.ts": $$$$$$70,
    "site/sections/Theme/Theme.tsx": $$$$$$68,
  },
  "matchers": {
    "site/matchers/canonical.ts": $$$$$$$0,
    "site/matchers/multipleCanonical.ts": $$$$$$$1,
  },
  "actions": {
    "site/actions/createReview.ts": $$$$$$$$$0,
  },
  "apps": {
    "site/apps/deco/records.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
